import { Fighter } from './fighters.model';

export const FIGHTERS_SEED: Fighter[] = [
  {
    id: '1',
    name: 'Dustin Poirier',
    nickname: 'The Diamond',
    weightDivision: 'Lightweight',
    country: 'United States',
    wins: 30,
    losses: 10,
    draws: 0,
    active: false,
  },
  {
    id: '2',
    name: 'Alex Pereira',
    nickname: 'Poatan',
    weightDivision: 'Light Heavyweight',
    country: 'Brazil',
    wins: 13,
    losses: 4,
    draws: 0,
    active: true,
  },
  {
    id: '3',
    name: 'Ilia Topuria',
    nickname: 'El Matador',
    weightDivision: 'Lightweight',
    country: 'Spain',
    wins: 17,
    losses: 1,
    draws: 0,
    active: true,
  },
  {
    id: '4',
    name: 'Merab Dvalishvili',
    nickname: 'The Machine',
    weightDivision: 'Bantamweight',
    country: 'Georgia',
    wins: 21,
    losses: 5,
    draws: 0,
    active: true,
  },
  {
    id: '5',
    name: 'Islam Makhachev',
    nickname: '',
    weightDivision: 'Lightweight',
    country: 'Russia',
    wins: 28,
    losses: 1,
    draws: 0,
    active: true,
  },
];
